# Generated by Django 5.2.6 on 2025-10-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='send_push_now',
            field=models.BooleanField(default=False, help_text='✓ Shëno për të dërguar push notification kur ruhet kuizi', verbose_name='Dërgo njoftim'),
        ),
    ]
