"""
Django settings for be_blog project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Vendos SECRET_KEY real ne .env (lokalisht) ose ne env vars te hosting-ut
# (prodhim). Vlera fallback ketu sherben vetem qe projekti te ngrihet pa
# .env — MOS e perdor ne prodhim.
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-dev-only-fallback-vendos-nje-SECRET_KEY-ne-.env',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').strip().lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv(
        'ALLOWED_HOSTS',
        '192.168.243.154,localhost,127.0.0.1,thesarislam.pythonanywhere.com,192.168.56.1',
    ).split(',') if h.strip()
]

# Render vendos vetiu kete env var me domain-in real (xxx.onrender.com) —
# shtoje automatikisht, s'ka nevoje ta japesh dore ne ALLOWED_HOSTS.
_render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if _render_hostname:
    ALLOWED_HOSTS.append(_render_hostname)

# Django 4+ kerkon qe origjina e kerkeses (Origin header) te jete e
# besueshme eksplicit per HTTPS POST (admin login etj.) — ndertohet nga
# ALLOWED_HOSTS, pa e mbajtur si liste te dyfishte per t'u sinkronizuar.
CSRF_TRUSTED_ORIGINS = [
    f'https://{h}' for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1')
]

if not DEBUG:
    # Render (dhe host-e te ngjashem) terminojne HTTPS ne proxy dhe e
    # percjellin kerkesen brenda si HTTP + header X-Forwarded-Proto — pa
    # kete, Django s'e njeh kerkesen si "secure" dhe redirect/cookie-t
    # e sigurta thyhen.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_api',
    'books_api',
    'quizes_api',
    'notifications_api',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.sites',
    'nested_admin',
    # 'channels'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'be_blog.urls'
SITE_ID = 1

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'be_blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# DATABASE_URL nga .env/env vars — p.sh. postgres://... per Neon/Render.
# Nese s'eshte vendosur ose eshte sqlite, perdor db.sqlite3 lokal (default
# i vjeter, i paprekur, per zhvillim).
_database_url = os.getenv('DATABASE_URL', '')
if _database_url and not _database_url.startswith('sqlite'):
    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Whitenoise sherben static files (admin CSS/JS etj.) direkt nga Django ne
# prodhim, pa nevoje per Nginx/CDN te vecante — mjafton per Render.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user_api.CustomUser'

REST_FRAMEWORK = {
'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # Perdorur nga user_api/throttling.py per te penguar brute-force ne
    # login/regjistrim/moderator-login — s'kishte asnje kufizim me pare.
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'register': '10/hour',
        'moderator_login': '5/min',
    },
}

#perkohesisht
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://192.168.243.154:8000", "https://thesarislam.pythonanywhere.com", "http://192.168.56.1:8000",
    "https://5def-109-234-233-158.ngrok-free.app"
]

# FIREBASE_CREDENTIALS_PATH ne .env eshte relativ (per zhvillim lokal) —
# nese jepet nje path absolut (p.sh. ne Render/Docker), perdore direkt.
_firebase_cred_env = os.getenv('FIREBASE_CREDENTIALS_PATH', '').strip()
if _firebase_cred_env:
    FIREBASE_CREDENTIALS_PATH = (
        _firebase_cred_env if os.path.isabs(_firebase_cred_env)
        else os.path.join(BASE_DIR, _firebase_cred_env)
    )
else:
    FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'firebase-credentials.json')

# Alternative per prodhim (Render etj.): disku eshte i perkohshem, s'ka ku
# te ngarkosh firebase-credentials.json fizikisht. Jep permbajtjen e plote
# te JSON-it, base64-enkoduar, si nje env var e vetme — shiko
# notifications_api/services.py._init_firebase() per perdorimin.
FIREBASE_CREDENTIALS_JSON_BASE64 = os.getenv('FIREBASE_CREDENTIALS_JSON_BASE64', '').strip()

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'books_api': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Channels për WebSocket
# ASGI_APPLICATION = 'project.asgi.application'
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelBackend',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }