# Generated by Django 5.2.6 on 2025-10-03 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('translator', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('edukateIslame', 'Edukate Islame'), ('jetaESahabeve', 'Jeta e Sahabeve'), ('historiteEProfeteve', 'Historitë e Profeteve'), ('historiNgaKurani', 'Histori nga Kurani'), ('namaziDheAdhurimet', 'Namazi dhe Adhurimet'), ('duatPerFemije', 'Duatë per Femije'), ('etikeDheVlera', 'Etike dhe Vlera'), ('ngjarjeInspiruese', 'Ngjarje Inspiruese'), ('anecdotaHumoristikeMeMesim', 'Anekdota Humoristike'), ('festeIslame', 'Feste Islame'), ('shkencaDheIslami', 'Shkenca dhe Islami'), ('artDheKreativitetIslamik', 'Art dhe Kreativitet'), ('rregullaTePerditshmeIslame', 'Rregulla te Perditshme'), ('tjeter', 'Tjeter')], max_length=50)),
                ('cover_image', models.URLField(blank=True, help_text='URL e jashtme (opsionale nëse ngarkon file)', max_length=500, null=True)),
                ('pdf_path', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_file', models.ImageField(blank=True, help_text='Ngarko imazh nga kompjuteri', null=True, upload_to='covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Njoftimi u dërgua')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Dërguar më')),
                ('notification_count', models.IntegerField(default=0, verbose_name='Nr. njoftimesh')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='books_api.book')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('book', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='PageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('content', models.TextField()),
                ('position', models.IntegerField()),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='books_api.bookpage')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
