# Generated by Django 5.2.6 on 2025-10-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='send_push_now',
            field=models.BooleanField(default=False, help_text='Aktivizoje për të dërguar push menjëherë kur ruan'),
        ),
    ]
