# Generated by Django 5.2.6 on 2025-10-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0002_book_send_push_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='send_push_now',
        ),
    ]
