# Generated by Django 5.2.6 on 2025-10-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0003_remove_book_send_push_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='send_push_now',
            field=models.BooleanField(default=False, help_text='✓ Shëno për të dërguar push notification kur ruhet libri', verbose_name='Dërgo njoftim'),
        ),
    ]
