# Generated by Django 5.2.6 on 2025-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0004_book_send_push_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
