# Generated by Django 5.2.6 on 2026-08-04 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ayah', 'Ajet Kuranor'), ('hadith', 'Hadith'), ('advice', 'Këshillë'), ('surah_audio', 'Sure e shkurtër (audio)')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='P.sh. "Ajeti i ditës" — opsionale, gjenerohet automatikisht nëse bosh.', max_length=255)),
                ('text', models.TextField(help_text='Teksti kryesor — ajeti/hadithi/këshilla në shqip.')),
                ('source', models.CharField(blank=True, help_text='P.sh. "Bukhari 1:1" ose "Sure El-Bekare, ajeti 255".', max_length=255)),
                ('explanation', models.TextField(blank=True, help_text='Shpjegim i shkurtër (tefsir/kontekst) — opsional.')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='daily_audio/')),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('audio_public_id', models.CharField(blank=True, max_length=255)),
                ('publish_date', models.DateField(help_text='Dita kur shfaqet — një përmbajtje për ditë.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('send_push_now', models.BooleanField(default=False, help_text='✓ Shëno për të dërguar push notification kur ruhet.', verbose_name='Dërgo njoftim')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Njoftimi u dërgua')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Content',
                'ordering': ['-publish_date'],
            },
        ),
    ]
